project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Khaled"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ahmed-Khaled-Saleh/
      - icon: linkedin
        href: https://www.linkedin.com/in/ahmedkhaledsaleh/
format:
  html:
    theme:
      # light: flatly
      dark: slate
    mainfont: cursive
    css: styles.css
    fontcolor: "#ffffff"
    linkcolor: "Blue"



