project:
  type: website
  output-dir: docs

website:
  title: "Ahmed Khaled"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Ahmed-Khaled-Saleh/
      - icon: linkedin
        href: https://www.linkedin.com/in/ahmedkhaledsaleh/
format:
  html:
    theme:
      light: yeti
      dark: solar
    mainfont: Arial
    css: styles.css



