---
title: "About"
about:
  template: jolla
  links:
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/ahmedkhaledsaleh/
    - icon: github
      text: Github
      href: https://github.com/Ahmed-Khaled-Saleh/
---

My name is Ahmed Khaled, you can call me Ahmed. I am a machine learning engineer and a Research Assistant. I am a Research Assistant at the  Intelligent Connectivity and Networks/Systems Group (ICON), Center for Wireless technology (CWC), University of Oulu, Finalnd. I work under the supervision of Prof. [Mehdi Bennis](https://sites.google.com/view/dr-mehdi-bennis/home). My main area of interests are machine learning, deep learning, Federated Learning, Natural Language Processing, reinforcement learning, and optimization. 


On the other side of the world, namely the industry, I am a machine learning engineer at [Revolution Data Platforms (RDP)](https://www.dataplatforms.ca/). RDP is a startup that specializes in building data platforms, data solutions, and anlytical workloads. I am responsible for the development of the machine learning models and the utilization ofLarge Language models(LLMs) to solve customer's specifc usecases. I mainly work with Azure Cloud, Python, and Pytorch.

For more information about my work, please check my [CV](./posts/Ahmed%20Khaled%20Resume.pdf).

This is my personal place on the internet where I create technical and non-technical content, and write about topics that I like and find interesting. I like to write because, first, like it, and second, I can see the gap in my knowledge when I write about something.